# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ddopnew',
                'doc_host': 'https://opimwue.github.io',
                'git_url': 'https://github.com/opimwue/ddopnew',
                'lib_path': 'ddopnew'},
  'syms': {'ddopnew.core': {'ddopnew.core.foo': ('core.html#foo', 'ddopnew/core.py')}}}
