# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/80_datasets/kaggle_m5.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/80_datasets/kaggle_m5.ipynb 3
import logging
logging.basicConfig(level=logging.INFO)

import numpy as np
import os
import pandas as pd
