"""Agents that knows the underlying task and the optimal action"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/30_agents/42_DP_agents/10_clairvoyant_agent.ipynb.

# %% auto 0
__all__ = ['ClairvoyantPolicy', 'ClairvoyantCoreAgent', 'ClairvoyantAgent']

# %% ../../../nbs/30_agents/42_DP_agents/10_clairvoyant_agent.ipynb 3
import logging

from abc import ABC, abstractmethod
from typing import Union, Optional, List
import numpy as np
import joblib
import os
import statsmodels.api as sm
from .utils import GLMLink
from ...envs.base import BaseEnvironment
from .mushroom_rl import PricingMushroomBaseAgent
from mushroom_rl.core import Agent
from ...utils import MDPInfo
from ..obsprocessors import FlattenTimeDimNumpy
from ...envs.actionprocessors import ClipAction

# %% ../../../nbs/30_agents/42_DP_agents/10_clairvoyant_agent.ipynb 4
class ClairvoyantPolicy():
    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] = None,
                 actionprocessors: Optional[List[object]] = None,
                 agent_name: str | None = None,
                 task: dict = None,
                 price_function = None,
                 g = None,
                 ):
        
        alpha = np.array(task["alpha"])
        beta = np.array(task["beta"])
        assert type(alpha) == type(beta), "alpha and beta must be of the same type"
        if type(alpha) == None:
            alpha = np.zeros(environment_info.observation_space['features'].shape[0])   
            beta = np.zeros(environment_info.observation_space['features'].shape[0])
        self.environment_info = environment_info
        self.task = task
        self.alpha = alpha
        self.beta = beta
        self.actionprocessors = actionprocessors
        self.price_function = price_function # Needs to return an np array
        self.g = g
        self.t = 0
        self.mode = "train"
        self.actionprocessors.append(ClipAction(environment_info.action_space.low, environment_info.action_space.high))

    def draw_action(self, observation: np.ndarray):
        X = observation['features']

        price = self.price_function(X, self.alpha, self.beta)
        
        for processor in self.actionprocessors:
            price = processor(price)
        
        return np.array(price)
    
    def update_env(self, env):
        self.environment_info = env.mdp_info
        self.task = env.get_task()
        
        self.alpha = env.alpha
        self.beta = env.beta
        """TODO add change in price function"""
    def fit(self, X, Y, action):
        pass
    
        
    def reset(self):
        pass
        

# %% ../../../nbs/30_agents/42_DP_agents/10_clairvoyant_agent.ipynb 5
class ClairvoyantCoreAgent(Agent):

    """
    Base class for clairvoyant agents.
    """

    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] = [],
                 actionprocessors: Optional[List[object]] = [],
                 agent_name: str | None = None,
                 task: dict = None,
                 price_function = None,
                 g = None,
                 ):
        
        policy = ClairvoyantPolicy(environment_info=environment_info, obsprocessors=obsprocessors, actionprocessors=actionprocessors, task=task, price_function=price_function, g=g)
        self.agent_name = agent_name
        super().__init__(environment_info, policy)
        
    def fit(self, dataset, **kwargs):
        X = dataset[0][0]["features"]
        Y = kwargs["demand"][0]
        action = dataset[0][1]
        self.policy.fit(X, Y, action)
        
    def update_env(self, env):
        self.policy.update_env(env)
        
    
        

# %% ../../../nbs/30_agents/42_DP_agents/10_clairvoyant_agent.ipynb 6
class ClairvoyantAgent(PricingMushroomBaseAgent):
    """
    Wrapper class for ClairvoyantCoreAgent to interact with MushroomRL.
    """
    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] =[],
                 actionprocessors: Optional[List[object]] = [],
                 agent_name: str | None = None,
                 task: dict = None,
                 price_function = None,
                 g = None,
                 ):
        self.agent = ClairvoyantCoreAgent(environment_info = environment_info,
                                     obsprocessors = obsprocessors, 
                                     actionprocessors = actionprocessors, 
                                     agent_name = agent_name, 
                                     task=task,
                                     price_function = price_function, 
                                     g = g)
        super().__init__(environment_info = environment_info, obsprocessors = obsprocessors, agent_name = agent_name)
    def update_env(self, env: object):
        """ Update the environment specific parameters of the agent """
        self.agent.update_env(env)
        
