"""Agents utelizing the ILQX approach for Dynamic pricing and learning problems from https://doi.org/10.1287/mnsc.2020.3680"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/30_agents/42_DP_agents/11_ILQX_agent.ipynb.

# %% auto 0
__all__ = ['ILQXPolicy', 'ILQXCoreAgent', 'ILQXAgent']

# %% ../../../nbs/30_agents/42_DP_agents/11_ILQX_agent.ipynb 3
import logging

from abc import ABC, abstractmethod
from typing import Union, Optional, List
import numpy as np
import joblib
import os
import statsmodels.api as sm
from .utils import GLMLink
from ...envs.base import BaseEnvironment
from .mushroom_rl import PricingMushroomBaseAgent
from mushroom_rl.core import Agent
from ...utils import MDPInfo
from ..obsprocessors import FlattenTimeDimNumpy


# %% ../../../nbs/30_agents/42_DP_agents/11_ILQX_agent.ipynb 4
class ILQXPolicy():
    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] = None,
                 actionprocessors: Optional[List[object]] = None,
                 agent_name: str | None = None,
                 ex_prices: np.ndarray | None = None,
                 alpha: np.ndarray | None = None,
                 beta: np.ndarray | None = None,
                 price_function = None,
                 g = None,
                 ):
        assert type(alpha) == type(beta), "alpha and beta must be of the same type"
        if alpha is None:
            alpha = np.zeros(environment_info.observation_space.shape[1])
            beta = np.zeros(environment_info.observation_space.shape[1])
        assert ex_prices.shape[0] >= 2

        self.environment_info = environment_info
        self.ex_prices = ex_prices
        self.alpha = alpha
        self.beta = beta
        self.actionprocessors = actionprocessors
        self.price_function = price_function # Needs to return an np array
        self.M = [[np.power(x,2)+i for x in range(1, int(np.sqrt(environment_info.horizon)))] for i in range(0, 2)]
        self.g = g
        self.t = 0
        self.X = np.empty((0, environment_info.observation_space.shape[1] * 2))
        self.Y = np.empty((0, 1))
        self.mode = "train"

    def draw_action(self, observation: np.ndarray):
        for idx, m in enumerate(self.M):
            if self.t in m:
                price = self.ex_prices[idx]
                break
        else:   
            price = self.price_function(observation, self.alpha, self.beta)
            
        for processor in self.actionprocessors:
            price = processor(price)
        
        return price
    
    def fit(self, X, Y, action):
        assert self.mode == "train"
        self.t += 1
        X = np.concatenate([X, X * action], axis=1)
        self.X = np.vstack([self.X, X])
        self.Y = np.vstack([self.Y, Y])
        self.parameter_update()
    
    def parameter_update(self):
        model = sm.GLM(self.Y, self.X, family=sm.families.Gamma())
        results = model.fit()
        self.alpha = results.params[self.environment_info.observation_space.shape[0]:]
        self.beta = results.params[:self.environment_info.observation_space.shape[0]]
        
    def reset(self):
        return

# %% ../../../nbs/30_agents/42_DP_agents/11_ILQX_agent.ipynb 5
class ILQXCoreAgent(Agent):

    """
    Base class for ILQX agents.
    """

    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] = [],
                 actionprocessors: Optional[List[object]] = [],
                 agent_name: str | None = None,
                 ex_prices: np.ndarray | None = None,
                 alpha: np.ndarray | None = None,
                 beta: np.ndarray | None = None,
                 price_function = None,
                 g = None,
                 ):
        
        policy = ILQXPolicy(environment_info=environment_info, obsprocessors=obsprocessors, actionprocessors=actionprocessors, ex_prices=ex_prices, alpha=alpha, beta=beta, price_function=price_function, g=g)
        self.agent_name = agent_name
        super().__init__(environment_info, policy)
        
    def fit(self, dataset, **kwargs):
        X = dataset[0][0][0]
        Y = kwargs["demand"][0]
        action = dataset[0][1]
        self.policy.fit(X, Y, action)



# %% ../../../nbs/30_agents/42_DP_agents/11_ILQX_agent.ipynb 6
class ILQXAgent(PricingMushroomBaseAgent):
    """
    Wrapper class for ILQXCoreAgent to interact with MushroomRL.
    """
    def __init__(self,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] =[],
                 actionprocessors: Optional[List[object]] = [],
                 agent_name: str | None = None,
                 ex_prices: np.ndarray | None = None,
                 alpha: np.ndarray | None = None,
                 beta: np.ndarray | None = None,
                 price_function = None,
                 g = None,
                 ):
        self.agent = ILQXCoreAgent(environment_info = environment_info,
                                   obsprocessors = obsprocessors, 
                                   actionprocessors = actionprocessors, 
                                   agent_name = agent_name, 
                                   ex_prices = ex_prices, 
                                   alpha = alpha, 
                                   beta = beta, 
                                   price_function = price_function, 
                                   g = g)
        super().__init__(environment_info = environment_info, obsprocessors = obsprocessors, agent_name = agent_name)
