"""Agents utelizing the TS based approach for Dynamic pricing and learning problems from https://doi.org/10.48550/arXiv.1604.07463"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/30_agents/42_DP_agents/12_TS_agent.ipynb.

# %% auto 0
__all__ = ['TSPolicy', 'TSCoreAgent', 'TSAgent']

# %% ../../../nbs/30_agents/42_DP_agents/12_TS_agent.ipynb 3
import logging

from abc import ABC, abstractmethod
from typing import Union, Optional, List
import numpy as np
import joblib
import os
import statsmodels.api as sm
from .utils import GLMLink
from ...envs.base import BaseEnvironment
from .mushroom_rl import PricingMushroomBaseAgent
from mushroom_rl.core import Agent
from ...utils import MDPInfo
from ..obsprocessors import FlattenTimeDimNumpy
from ...envs.actionprocessors import ClipAction


# %% ../../../nbs/30_agents/42_DP_agents/12_TS_agent.ipynb 4
class TSPolicy():
    def __init__(self,
                 lam: float,
                 reg: float,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] = None,
                 actionprocessors: Optional[List[object]] = None,
                 agent_name: str | None = None,
                 ex_prices: np.ndarray | None = None,
                 alpha: np.ndarray | None = None,
                 beta: np.ndarray | None = None,
                 price_function = None,
                 g = None,
                 ):
        assert type(alpha) == type(beta), "alpha and beta must be of the same type"
        if alpha is None:
            alpha = np.zeros(environment_info.observation_space['features'].shape[1])
            beta = np.zeros(environment_info.observation_space['features'].shape[1])
        if isinstance(ex_prices, list):
            ex_prices = np.array(ex_prices)
        assert ex_prices.shape[0] >= 2

        self.environment_info = environment_info
        self.ex_prices = ex_prices
        self.alpha = alpha
        self.beta = beta
        self.actionprocessors = actionprocessors
        self.price_function = price_function # Needs to return an np array
        self.lam = lam
        self.reg = reg
        self.g = g
        self.t = 0
        self.X = np.empty((0, environment_info.observation_space['features'].shape[1] * 2))
        self.Y = np.empty((0, 1))
        self.mode = "train"
        self.actionprocessors.append(ClipAction(environment_info.action_space.low, environment_info.action_space.high))

    def draw_action(self, observation: np.ndarray):
        if self.t in [0, 1]:
            prices = self.ex_prices[self.t]
        else:
            prices = np.empty(0)
            X = observation['features']
            for x in X:   
                M = self.compute_uncertainty_M(x)
                noise = np.random.multivariate_normal(np.zeros(2), np.identity(2))         
                M = np.linalg.inv(M)
                M = np.linalg.cholesky(M).T
                norm = M @ noise
                norm = (1/self.environment_info.observation_space.shape[1]) * norm
                alpha = self.alpha + norm[0]
                beta = self.beta + norm[1]
                price = self.price_function(x, alpha, beta)
                prices = np.append(prices, price)
                
        for processor in self.actionprocessors:
            prices = processor(prices)
        
        return prices
    
    def sample_design_matrix(self):
        I = np.identity(2*self.environment_info.observation_space['features'].shape[1])
        I_lamdba = self.lam * I
        if self.X.shape[0] == 0:
            return I_lamdba
        matrix = np.sum([np.outer(x, x.T) for x in self.X], axis=0)
        return I_lamdba + matrix
    
    def compute_uncertainty_M(self, x_t):
        M = self.sample_design_matrix()
        block_matrix = np.block([
            [x_t, np.zeros_like(x_t)],
            [np.zeros_like(x_t), x_t]
        ])
        M_inverse = np.linalg.inv(M)

        projected_matrix = block_matrix @ M_inverse @ block_matrix.T
        projected_matrix_inverse = np.linalg.inv(projected_matrix)
        return projected_matrix_inverse
    
    def fit(self, X, Y, action):
        assert self.mode == "train"
        self.t += 1
        X= X[0]
        X = np.concatenate([X, X * action])
        self.X = np.vstack([self.X, X])
        self.Y = np.vstack([self.Y, Y])
        self.parameter_update()
    
    def parameter_update(self):
        if self.X.shape[0] < 2:
            return
        model = sm.GLM(self.Y, self.X, family=sm.families.Binomial())
        results = model.fit()
        self.alpha = results.params[:self.environment_info.observation_space['features'].shape[1]]
        self.beta = results.params[self.environment_info.observation_space['features'].shape[1]:]
    
    def update_env(self, env):
        self.environment_info = env.mdp_info
        self.X = np.empty((0, self.environment_info.observation_space['features'].shape[1] * 2))
        self.Y = np.empty((0, 1))
        self.actionprocessors[-1] = ClipAction(self.environment_info.action_space.low, self.environment_info.action_space.high)
        self.M = [[np.power(x,2)+i for x in range(0, int(np.sqrt(self.environment_info.horizon)))] for i in range(0, 2)]
        self.t = 0 
        
    def reset(self):
        return

# %% ../../../nbs/30_agents/42_DP_agents/12_TS_agent.ipynb 5
class TSCoreAgent(Agent):
    """
    Base class for TS agents.
    """

    def __init__(self,
                    lam: float,
                    reg: float,
                    environment_info: MDPInfo,
                    obsprocessors: Optional[List[object]] = [],
                    actionprocessors: Optional[List[object]] = [],
                    agent_name: str | None = None,
                    ex_prices: np.ndarray | None = None,
                    alpha: np.ndarray | None = None,
                    beta: np.ndarray | None = None,
                    price_function = None,
                    g = None,
                    ):
        
        policy = TSPolicy(lam=lam, reg=reg, environment_info=environment_info, obsprocessors=obsprocessors, actionprocessors=actionprocessors, ex_prices=ex_prices, alpha=alpha, beta=beta, price_function=price_function, g=g)
        self.agent_name = agent_name
        super().__init__(environment_info, policy)
        
    def fit(self, dataset, **kwargs):
        X = dataset[0][0]['features']
        Y = kwargs["demand"][0]
        action = dataset[0][1]
        self.policy.fit(X, Y, action)
    def update_env(self, env):
        self.policy.update_env(env)

# %% ../../../nbs/30_agents/42_DP_agents/12_TS_agent.ipynb 6
class TSAgent(PricingMushroomBaseAgent):
    """
    Wrapper class for TSCoreAgent to interact with MushroomRL.
    """
    def __init__(self,
                 lam: float,
                 reg: float,
                 environment_info: MDPInfo,
                 obsprocessors: Optional[List[object]] =[],
                 actionprocessors: Optional[List[object]] = [],
                 agent_name: str | None = None,
                 ex_prices: np.ndarray | None = None,
                 alpha: np.ndarray | None = None,
                 beta: np.ndarray | None = None,
                 price_function = None,
                 g = None,
                 ):
        self.agent = TSCoreAgent(lam=lam, reg=reg, environment_info=environment_info,
                                 obsprocessors=obsprocessors, 
                                 actionprocessors=actionprocessors, 
                                 agent_name=agent_name, 
                                 ex_prices=ex_prices, 
                                 alpha=alpha, 
                                 beta=beta, 
                                 price_function=price_function, 
                                 g=g)
        super().__init__(environment_info=environment_info, obsprocessors=obsprocessors, agent_name=agent_name)
    def update_env(self, env: object):
        """ Update the environment specific parameters of the agent """
        self.agent.update_env(env)
