# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/40_base_agents/11_basic_agents.ipynb.

# %% auto 0
__all__ = ['RandomAgent']

# %% ../../nbs/40_base_agents/11_basic_agents.ipynb 3
from abc import ABC, abstractmethod
from typing import Union
import numpy as np

from ..envs.base import BaseEnvironment
from .base import BaseAgent

# %% ../../nbs/40_base_agents/11_basic_agents.ipynb 4
class RandomAgent(BaseAgent):
    
    train_mode = "direct_fit"

    def __init__(self, environment_info):

        self.mode = "train"
        super().__init__(environment_info)

    def draw_action(self, observation):
        return self.environment_info.action_space.sample()

    def fit(self, X, Y):
        assert self.mode == "train"
        pass
